basic_blog/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/edit/<str:username>', views.edit_profile, name="edit_profile"),
    path('profile/<str:user_name>', views.profile, name="profile"),
    path('profile/password/<str:user>/', views.change_password, name="change_password"),
    path('delete/<str:username>/', views.delete_profile, name='delete'),

]

basic_blog/basic_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from blobing import views as blobing_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blobing.urls')),
    path('accounts/', include('accounts.urls')),
    path('', blobing_views.home, name ='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic_blog/blobing/urls.py
from django.urls import path
from . import views

app_name = 'blobing'

urlpatterns = [
    path('', views.home , name = 'home'),
    path('articles', views.Articles, name = 'articles'),
    path ('details/<int:id>' , views.details , name = 'details'),
    path ('search_blogs' , views.search_blogs , name = 'search-blogs'),
    path('edit/<int:id>', views.edit_blog , name='edit-blogs'),
    path('delete_blog/<int:id>/', views.delete_blog, name='delete-blogs'),     
]

basic_blog/accounts/models.py
from django.db import models

# Create your models here.

basic_blog/blobing/models.py
from django.db import models
import readtime
from django.contrib.auth.models import User



# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", blank=True )
    status = models.IntegerField(choices=STATUS, default=1) 
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    
    

    def __str__(self):
        return self.title


    def snippet(self):
        return self.body[:100] + '...'   
    
    def get_readtime(self):
        result = readtime.of_text(self.body)
        return result.text

basic_blog/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
from django.contrib.auth.models import User  
# from django.contrib.auth.forms import UserCreationForm
      
class SignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'class':'form-control','Placeholder': 'Enter username'})
        self.fields['first_name'].widget.attrs.update({'class':'form-control','Placeholder': 'Enter your first name here'})
        self.fields['last_name'].widget.attrs.update({'class':'form-control','Placeholder': 'Enter your last name here'})
        self.fields['email'].widget.attrs.update({'class':'form-control','Placeholder': 'Enter your E-Mail here'})
        self.fields['password1'].widget.attrs.update({'class':'form-control','Placeholder': 'Enter your password'})
        self.fields['password2'].widget.attrs.update({'class':'form-control','Placeholder': 'Confirm your Password'})


    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField(max_length=200)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
       
class UpdateUserForm(UserChangeForm):
   
    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField(max_length=200)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

basic_blog/blobing/forms.py
from django import forms
from .models import Article
from ckeditor.fields import RichTextField

class CreateArticle(forms.ModelForm):
  body =RichTextField()
  class Meta:
    model = Article
    fields = ["title", "body", "thumb", "status"]




  def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)

      self.fields['title'].widget.attrs.update({'class':'form-control','Placeholder': 'Title here.'})
      #self.fields['body'].widget.attrs.update({'class':'form-control','Placeholder': 'Enter your blog here.'})
      self.fields['status'].widget.attrs.update({'class':'form-control','class':'form-select'})
      self.fields['thumb'].widget.attrs['class'] = 'form-control'


class UpdateArticleForm(forms.ModelForm):
  class Meta:
    model = Article
    fields = ["title", "body", "thumb", "status"]

basic_blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def signup_view(request):
    if request.method== "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('blobing:home')    
    else:
        form = UserCreationForm()   
    return render (request, 'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method =='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect ('blobing:home')
    else:
        form = AuthenticationForm()
    return render (request, 'accounts/login.html',{'form':form})    

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect ('blobing:home')

basic_blog/basic_blog/views.py
from django.http import HttpResponse

def home(request):
    return HttpResponse('''<h1> This is a homepage </h1> <br>
    <h2> Hello everyone !! </h2>  <p> how is everythin going..!! </p>''')

    

basic_blog/blobing/views.py
from django.shortcuts import render, redirect
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from . models import Article
from .  import forms
from django.contrib.auth.decorators import login_required

# Create your views here.

def search_blogs(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        articles = Article.objects.filter(title__contains=searched)

        return render(request,'blobing/search.html', {'searched': searched,'articles':articles})
    else:
        return render(request,'blobing/search.html')


def home(request):
    article = Article.objects.all().order_by('-pub_date') #have removed this 
    # set up pagination
    p = Paginator(Article.objects.order_by('-pub_date'), 2) 
    page = request.GET.get('page')
    articles = p.get_page(page)
    nums = "a" * articles.paginator.num_pages

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request,'blobing/home.html', {'articles':articles,'nums':nums, 'num_visits':num_visits})
    
     

@login_required(login_url='/accounts/login')
def Articles(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            Instance=form.save(commit=False)
            Instance.author=request.user
            Instance.save()
            return redirect ('blobing:home')
    else:
        form = forms.CreateArticle()
    return render (request, 'blobing/index.html', {'form': form})


def details(request , id):
    article = Article.objects.get(id=id)
    return render (request, 'blobing/details.html', {'article': article})

basic_blog/accounts/templates/accounts/change_password.html
{% extends 'blobing/base_layout.html' %}

{%  block content %}
<form method="post">
    {% csrf_token %}
</br>
<div class="container text-center  card bg-light w-50">
    <div class="card-header">
     <h3>  Change Password </h3>
    </div></br>
<div class="col-lg-10 ">
    <label for="inputPassword5" class="form-label col-lg-4">Old Password</label>
    {{form.old_password}}
 </div></br>
 <div id="passwordHelpBlock" class="form-text">
 <pre>             <i class="fa-solid fa-circle-info"></i> Your password can’t be too similar to your other personal information.
        <i class="fa-solid fa-circle-info"></i> Your password must contain at least 8 characters.
        <i class="fa-solid fa-circle-info"></i> Your password can’t be a commonly used password.
        <i class="fa-solid fa-circle-info"></i> Your password can’t be entirely numeric. 
 </pre>   
</div>
    <div class="col-lg-10">
    <label for="inputPassword5" class="form-label col-lg-4">New Password</label>
    {{form.new_password1}}
 </div></br>
 <div class="col-lg-10">
    <label for="inputPassword5" class="form-label col-lg-4">Confirm New Password</label>
   {{form.new_password2}}
 </div></br>
 <div class="container text-center d-grid gap-2 col-6 mx-auto" >
 <button type="submit" class="btn btn-dark"> Confirm Change </button>
 </div>

</div>
</br>
</form>
{% endblock %}

basic_blog/accounts/templates/accounts/deleteaccount.html
<form method="post" >
     {% csrf_token %} 
    <p>Are you sure to delete "{{user.username}}"?</p>
     <button type="submit" value="confirm"> delete account</button>

</form>

basic_blog/accounts/templates/accounts/edit_profile.html
{% extends 'blobing/base_layout.html' %}


{% block content %}
{{ form.as_p }}




<!-- <form method="post">
    <div class="container bg-dark">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card ">
                    {% csrf_token %}
                    <div class="card-body">
                        <h2 class="card-title">Sign up</h2></br>
                        <label for="fname" class="form-label"> First Name </label></br>
                        {{ form.first_name }} </br>
                        <label for="lname" class="form-label">Last Name </label>
                        {{ form.last_name }} </br>
                        <div class="col-6">
                            <label for="username" class="form-label"> Username </label>
                            {{ form.username }} </br>
                        </div>
                        <label for="email" class="form-label">E-Mail</label>
                        {{ form.email }} </br>
                        <div class="col-8">
                            <label for="password" class="form-label">Password</label>
                            {{ form.password1 }} </br>
                        </div>
                        <div class="col-md-8">
                            <label for="confirm password" class="form-label">Confirm Password</label>
                            {{ form.password2 }} </br>
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary"> Sign in </button>
                        </div>
                        <div class="card-footer text-muted text-center">
                            Already have an account? <a href="{% url 'accounts:login' %}"> Log in</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form> -->
{% endblock %}

basic_blog/accounts/templates/accounts/login.html
{% extends 'blobing/base_layout.html' %}

{% block content %}
<br/>
<center>

<form method="post" action="{% url 'accounts:login' %}">    
<h1>  Log in: </h1>
    {% csrf_token %}
    {{ form.as_p }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <button type="submit"> Login </button> 
</form>

</center>
{%  endblock %}

basic_blog/accounts/templates/accounts/profile.html
{% extends 'blobing/base_layout.html' %}
{% load static %}
{% block content %}

<div class="card mb-3 my-3 p-3" >
    <div class="row g-0">
        <div class="col-md-4">
        <img src="{% static 'default.jpg' %}" class="img-fluid rounded-start" alt="">
        </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{ user.username }}</h5>
            <p class="card-text">  </p>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
        </div>
        </div>
    </div>
    </div>

<div class="container">
<div class="card ">

<h5 class="card-header"> {{ user.username }}'s Profile</h5>
<div class="card-body">
    <h5 class="card-title">Hello!! &nbsp; <strong> {{ user.username }} </strong></h5></br>
    {% if user.first_name %}
    <p class="card-text">First Name : &nbsp; &nbsp; {{ user.first_name }} </p><hr>
    {% else %}
    <div class="alert alert-warning" role="alert">
        <strong>First Name</strong> not provided by the user!
    </div> <hr> 
    {% endif %}
    {% if user.last_name %}
    <p class="card-text">last Name : &nbsp; &nbsp; {{ user.last_name }} </p><hr>
    {% else %}
    <div class="alert alert-warning" role="alert">
        <strong>Last Name</strong> not provided by the user!
    </div> <hr>
    {% endif %}
    {% if user.username %}
    <p class="card-text"> Username : &nbsp; &nbsp; {{ user.username }} </p><hr>
    {% else %}
    <div class="alert alert-warning" role="alert">
        <strong>Username</strong> not provided by the user!
    </div> <hr>
    {% endif %}
    {% if user.email %}
    <p class="card-text">Email : &nbsp; &nbsp; {{ user.email}} </p><hr>
    {% else %}
    <div class="alert alert-warning" role="alert">
        <strong>Email</strong> not provided by the user!
    </div> <hr>
    {% endif %}
    <div class="text-center">
    <a href="#" class="btn btn-info" type="button" > Edit Profile </a>
    <a href="{% url 'accounts:change_password' user.username %}" class="btn btn-primary" type="button" > Change Password   </a>
    <a href="{% url 'accounts:delete' user.username %}" class="btn btn-danger" type="button" > Delete Profile </a>
    </div>
</div>
</div>
<hr>
<h3> My Posts</h3>
</div>
{% for data in user_related_data %}
<div class="container">
<div class="card" >
    <div class="card-body">
      <blockquote class="blockquote mb-0">   
           <p>  <a href= " {% url 'blobing:details' data.id %} ">  {{ data.title }} </a> </p>
        </blockquote>
    </div>
    <div class="card-footer">
        <a href="{% url 'blobing:edit-blogs' data.id %}" class="btn btn-info" type="button" > Edit Blog </a>
        <a href="#" class="btn btn-danger" type="button" > Delete Blog </a>
    </div>
  </div>
</div>
  {% endfor %}
<!-- <span class="badge text-bg-primary">Primary</span> -->

{% endblock %}

basic_blog/accounts/templates/accounts/signup.html
{% extends 'blobing/base_layout.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}


<form ALIGN="center" method="post" class="sign-up-form">
    <h1> Sign up : </h1>
    {% csrf_token %}
    {% bootstrap_form form  %} 
    <!-- <button type="submit"> Sign up </button> -->
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}

</form>
{% endblock %}

basic_blog/blobing/templates/blobing/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blobing/style.css' %}" >
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title> The Blobing Blog</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
<div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blobing:home' %}"> <img src= "{% static 'B.jpg'  %}" width="50px"><img src="{% static 'B.jpg'  %}" width="50px"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'blobing:home' %}">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'blobing:articles' %}">Create Blog</a>
        </li>
    </ul>
    <form class="d-flex" role="search" method="POST" action="{% url 'blobing:search-blogs' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <div style="padding: 0px 10px" > 
        {% if user.is_authenticated %} 
    <form  method="post" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <button class="btn btn-outline-dark" type="submit"> logout </button> 
    </form>                
        {% else %}
        <a class="btn btn-outline-dark" href="{% url 'accounts:login' %}">Log In</a>
        <a class="btn btn-outline-dark" href="{% url 'accounts:signup' %}">Sign Up</a>
        {% endif %} 
    </div>
    </div>
</div>
</nav>
<header class="header">
    <h1 > The Blobing Blog </h1>
    {% if user.is_authenticated %}
    Hello {{ user.username }} !! 
    {% else %}
    <p><small>By <em> Yash Raj </em></small></p>
    {% endif %}    
</header>

{% block content %}

{% endblock content %}



</body>
</html>

basic_blog/blobing/templates/blobing/delete_blog.html
<form method="post">
    {% csrf_token %}
   Are you sure you want to delete {{ form.article }}
   <button type="submit"> Delete </button> 
</form>

basic_blog/blobing/templates/blobing/details.html
{% extends "blobing/base_layout.html" %}
{% load humanize %}
{%  load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'blobing/style.css' %}" >
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div class="article-detail">
  <div class="card">
    <div class="card-body">
    <h1> {{ article.title }} </h1>
    <h5>  Article by : {{ article.author}} </h5>
    <p>   {{article.get_readtime}} Read </p>
    <img style="width: 800px;"  src="{{ article.thumb.url }}"><br/><br/>
    <pre>  {{ article.body }} </pre>
    <p>  {{ article.pub_date|naturaltime }} </p>
    </div>
  </div>
</div>


{% endblock %}

basic_blog/blobing/templates/blobing/edit_blogs.html
{% extends "blobing/base_layout.html" %}
{% load humanize %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'blobing/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div class="container">
<div class="card">
  <div class="card-body">
    <form method="post" >  
      {% csrf_token %}
    <h1> {{ form.title }} </h1>
    <pre>  {{ form.body}} </pre>
    <div>
    </div>
    <img style="width: 800px;" src="{{ article.thumb.url }}"><br /> {{form.thumb}} <br />
    <button type="submit" class="btn btn-primary">Update</button>
    {{form.status}}
  </form>
  
  </div>
 
</form>
</div>
</div>

{% endblock %}

basic_blog/blobing/templates/blobing/home.html
{% extends 'blobing/base_layout.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'blobing/style.css' %}" >

<!-- <header>
  <h1 > The Blobing Blog </h1>
  <p>
    <small>By <em> Yash Raj </em></small>
  </p>    
</header> -->
 
<div class="container">
    {% for i in articles %}
          <div class="card">
            <div class="card-body">

        <h2><a href='{% url "blobing:details" i.id %}'>{{ i.title }}</a></h2>
          <p>   {{ i.get_readtime }} Read </p>
          <p> {{ i.snippet }} </p>
          <p> {{ i.pub_date }}</p>
          <br>
            </div>
          </div>  
    {% endfor %}
</div>
<br/><br/>


<!---
{{ articles }}<br/>
Has previous : {{ articles.has_previous }} <br/>
Has Next : {{ articles.has_next }} <br/>
Current page : {{ articles.number }} <br/>
Number of pages : {{ articles.paginator.num_pages }}
<hr> <br/> <br/>
-->

<center>You have visited this site {{ num_visits }} time{{ num_visits|pluralize }}.</center>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
  {% if articles.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1"> &laquo; First </a></li>
    <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}"> Previous </a></li>


  {% endif %}

  <li class="page-item "> <a class="page-link" href="#" >Page {{ articles.number }} of {{ articles.paginator.num_pages }} </a></li> 

  {% for i in nums %}
    <li class="page-item"> <a class="page-link" href="?page= {{ forloop.counter }}">{{ forloop.counter }}</a></li>

  {% endfor %}

  {% if articles.has_next %}
    <li class="page-item"><a class="page-link" href="?page= {{ articles.next_page_number }}"> Next </a></li>
    <li class="page-item"><a class="page-link" href="?page= {{ articles.paginator.num_pages }}"> Last &raquo; </a></li>
  {% endif %}

  </ul>
</nav>

{% endblock content %}

basic_blog/blobing/templates/blobing/index.html
{% extends 'blobing/base_layout.html'%}

{% load static %}
{% load bootstrap5 %}

<link rel="stylesheet" href="{% static 'blobing/style.css' %}" >

{% block content %}
<center>
<div class="container p-3 my-3 bg-dark text-white">
    <form action="{% url 'blobing:articles' %}" method="post" enctype="multipart/form-data">
      
        <br/>
        <h1> Create your Blog here:</h1><br/>
        {% csrf_token %}
        <div class="col-sm-10">    
        {{ form.title }}</br>
        </div>
        <div class="col-sm-10 ">
            {{ form.body }}
        </br>
            {{ form.body.help_text }}
        </br>
        </div></br>
        <div class="col-sm-5" >
        {{ form.thumb }}</br>
        </div>
        <div class="col-sm-5 dropdown-toggle dropdown-toggle-split">
        {{ form.status }}</br>
        </div>
        <button type="submit" class="btn btn-primary">Create</button><br/>
        <br/>
        {{ form.media }}
    </form>
</div>
</center>
<br/>
{% endblock %}

basic_blog/blobing/templates/blobing/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

basic_blog/blobing/templates/blobing/search.html
{% extends 'blobing/base_layout.html' %}

{% block content %}

    <center>
        {% if searched %}
        <h2> You searched for {{ searched }}</h2>
        <br/>
        {% for article in articles %}
        <a href="{% url 'blobing:details' article.id %} "> {{ article }} </a> <br/>
        {% endfor %}

        {% else %}
        <h1> Hey! you forgot to type </h1>
        {% endif %}
    </center>
   
       
{% endblock content %}